export const FILTER = 'FILTER';

export const ADD_PROTEIN_CLICK = 'ADD_PROTEIN_CLICK';
export const ADD_PROTEIN_REQUEST = 'ADD_PROTEIN_REQUEST';
export const ADD_PROTEIN_SUCCESS = 'ADD_PROTEIN_SUCCESS';
export const ADD_PROTEIN_FAILED = 'ADD_PROTEIN_FAILED';

export const REMOVE_PROTEIN_CLICK = 'REMOVE_PROTEIN_CLICK';
export const REMOVE_PROTEIN_REQUEST = 'REMOVE_PROTEIN_REQUEST';
export const REMOVE_PROTEIN_SUCCESS = 'REMOVE_PROTEIN_SUCCESS';
export const REMOVE_PROTEIN_FAILED = 'REMOVE_PROTEIN_FAILED';

export const UPDATE_PROTEIN_CLICK = 'UPDATE_PROTEIN_CLICK';
export const UPDATE_PROTEIN_REQUEST = 'UPDATE_PROTEIN_REQUEST';
export const UPDATE_PROTEIN_SUCCESS = 'UPDATE_PROTEIN_SUCCESS';
export const UPDATE_PROTEIN_FAILED = 'UPDATE_PROTEIN_FAILED';

export const MOVE_PROTEIN = 'MOVE_PROTEIN';

// export const SELECT_PROTEIN = 'SELECT_PROTEIN';
// export const FETCH_PROTEIN = 'FETCH_PROTEIN';
// export const RECEIVE_PROTEIN = 'RECEIVE_PROTEIN';
// export const REQUEST_PROTEIN = 'REQUEST_PROTEIN';

export const ADD_SPECIES_CLICK = 'ADD_SPECIES_CLICK';
export const ADD_SPECIES_REQUEST = 'ADD_SPECIES_REQUEST';
export const ADD_SPECIES_SUCCESS = 'ADD_SPECIES_SUCCESS';
export const ADD_SPECIES_FAILED = 'ADD_SPECIES_FAILED';

export const REMOVE_SPECIES_CLICK = 'REMOVE_SPECIES_CLICK';
export const REMOVE_SPECIES_REQUEST = 'REMOVE_SPECIES_REQUEST';
export const REMOVE_SPECIES_SUCCESS = 'REMOVE_SPECIES_SUCCESS';
export const REMOVE_SPECIES_FAILED = 'REMOVE_SPECIES_FAILED';

export const UPDATE_SPECIES_CLICK = 'UPDATE_SPECIES_CLICK';
export const UPDATE_SPECIES_REQUEST = 'UPDATE_SPECIES_REQUEST';
export const UPDATE_SPECIES_SUCCESS = 'UPDATE_SPECIES_SUCCESS';
export const UPDATE_SPECIES_FAILED = 'UPDATE_SPECIES_FAILED';

export const MOVE_SPECIES = 'MOVE_SPECIES';

export const SELECT_DATA = 'SELECT_DATA';
export const FETCH_DATA = 'FETCH_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const REQUEST_DATA = 'REQUEST_DATA';
