export const FILTER = 'FILTER';

export const ADD_PROTEIN_CLICK = 'ADD_PROTEIN_CLICK';
export const ADD_PROTEIN_REQUEST = 'ADD_PROTEIN_REQUEST';
export const ADD_PROTEIN_SUCCESS = 'ADD_PROTEIN_SUCCESS';
export const ADD_PROTEIN_FAILED = 'ADD_PROTEIN_FAILED';

export const REMOVE_PROTEIN_CLICK = 'REMOVE_PROTEIN_CLICK';
export const REMOVE_PROTEIN_REQUEST = 'REMOVE_PROTEIN_REQUEST';
export const REMOVE_PROTEIN_SUCCESS = 'REMOVE_PROTEIN_SUCCESS';
export const REMOVE_PROTEIN_FAILED = 'REMOVE_PROTEIN_FAILED';

export const UPDATE_PROTEIN_CLICK = 'UPDATE_PROTEIN_CLICK';
export const UPDATE_PROTEIN_REQUEST = 'UPDATE_PROTEIN_REQUEST';
export const UPDATE_PROTEIN_SUCCESS = 'UPDATE_PROTEIN_SUCCESS';
export const UPDATE_PROTEIN_FAILED = 'UPDATE_PROTEIN_FAILED';

export const MOVE_PROTEIN = 'MOVE_PROTEIN';

export const ADD_SPECIES_CLICK = 'ADD_SPECIES_CLICK';
export const ADD_SPECIES_REQUEST = 'ADD_SPECIES_REQUEST';
export const ADD_SPECIES_SUCCESS = 'ADD_SPECIES_SUCCESS';
export const ADD_SPECIES_FAILED = 'ADD_SPECIES_FAILED';

export const REMOVE_SPECIES_CLICK = 'REMOVE_SPECIES_CLICK';
export const REMOVE_SPECIES_REQUEST = 'REMOVE_SPECIES_REQUEST';
export const REMOVE_SPECIES_SUCCESS = 'REMOVE_SPECIES_SUCCESS';
export const REMOVE_SPECIES_FAILED = 'REMOVE_SPECIES_FAILED';

export const UPDATE_SPECIES_CLICK = 'UPDATE_SPECIES_CLICK';
export const UPDATE_SPECIES_REQUEST = 'UPDATE_SPECIES_REQUEST';
export const UPDATE_SPECIES_SUCCESS = 'UPDATE_SPECIES_SUCCESS';
export const UPDATE_SPECIES_FAILED = 'UPDATE_SPECIES_FAILED';

export const MOVE_SPECIES = 'MOVE_SPECIES';

export const ADD_GENOME_CLICK = 'ADD_GENOME_CLICK';
export const ADD_GENOME_REQUEST = 'ADD_GENOME_REQUEST';
export const ADD_GENOME_SUCCESS = 'ADD_GENOME_SUCCESS';
export const ADD_GENOME_FAILED = 'ADD_GENOME_FAILED';

export const REMOVE_GENOME_CLICK = 'REMOVE_GENOME_CLICK';
export const REMOVE_GENOME_REQUEST = 'REMOVE_GENOME_REQUEST';
export const REMOVE_GENOME_SUCCESS = 'REMOVE_GENOME_SUCCESS';
export const REMOVE_GENOME_FAILED = 'REMOVE_GENOME_FAILED';

export const UPDATE_GENOME_CLICK = 'UPDATE_GENOME_CLICK';
export const UPDATE_GENOME_REQUEST = 'UPDATE_GENOME_REQUEST';
export const UPDATE_GENOME_SUCCESS = 'UPDATE_GENOME_SUCCESS';
export const UPDATE_GENOME_FAILED = 'UPDATE_GENOME_FAILED';

export const MOVE_GENOME = 'MOVE_GENOME';

export const ADD_SYSTEMIC_EFFECT_CLICK = 'ADD_SYSTEMIC_EFFECT_CLICK';
export const ADD_SYSTEMIC_EFFECT_REQUEST = 'ADD_SYSTEMIC_EFFECT_REQUEST';
export const ADD_SYSTEMIC_EFFECT_SUCCESS = 'ADD_SYSTEMIC_EFFECT_SUCCESS';
export const ADD_SYSTEMIC_EFFECT_FAILED = 'ADD_SYSTEMIC_EFFECT_FAILED';

export const REMOVE_SYSTEMIC_EFFECT_CLICK = 'REMOVE_SYSTEMIC_EFFECT_CLICK';
export const REMOVE_SYSTEMIC_EFFECT_REQUEST = 'REMOVE_SYSTEMIC_EFFECT_REQUEST';
export const REMOVE_SYSTEMIC_EFFECT_SUCCESS = 'REMOVE_SYSTEMIC_EFFECT_SUCCESS';
export const REMOVE_SYSTEMIC_EFFECT_FAILED = 'REMOVE_SYSTEMIC_EFFECT_FAILED';

export const UPDATE_SYSTEMIC_EFFECT_CLICK = 'UPDATE_SYSTEMIC_EFFECT_CLICK';
export const UPDATE_SYSTEMIC_EFFECT_REQUEST = 'UPDATE_SYSTEMIC_EFFECT_REQUEST';
export const UPDATE_SYSTEMIC_EFFECT_SUCCESS = 'UPDATE_SYSTEMIC_EFFECT_SUCCESS';
export const UPDATE_SYSTEMIC_EFFECT_FAILED = 'UPDATE_SYSTEMIC_EFFECT_FAILED';

export const MOVE_SYSTEMIC_EFFECT = 'MOVE_SYSTEMIC_EFFECT';

export const SELECT_DATA = 'SELECT_DATA';
export const FETCH_DATA = 'FETCH_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const REQUEST_DATA = 'REQUEST_DATA';
